export const POKEMONS_ACTION_TYPES = {
  ADD_POKEMON_TO_CAUGHT_LIST: "pokemons/ADD_POKEMON_TO_CAUGHT_LIST",
  SET_SEARCH: "pokemons/SET_SEARCH",
  FETCH_POKEMONS_START: "pokemons/FETCH_POKEMONS_START",
  FETCH_POKEMONS_SUCCESS: "pokemons/FETCH_POKEMONS_SUCCESS",
  FETCH_POKEMONS_FAILURE: "pokemons/FETCH_POKEMONS_FAILURE",
}
